### PR TITLE
RHMWRT-62 and RHOAR-112: Remove ISTIO examples

### PR DESCRIPTION
**Pull request by gastaldi**
Missions and Boosters have been renamed to example applications and some of the functionality of the missions and boosters are now provided as capabilities. Other missions and boosters are also not really good as example applications since they are only focusing on showing a particular feature of Istio/Service Mesh.
The following mission should be removed since these are better surfaced as Istio examples and not connected to a particular runtime.

- Istio - Routing
- Istio - Security
- Istio - Circuit Breaker

### CODE REVIEW

**Comment by geoand** [comment]
cc @metacosm

**Comment by Ladicek** [comment]
Why did you delete _Istio - Distributed Tracing_?

**Comment by gastaldi** [comment]
Oh I thought that example would fall in the `The following mission should be removed since these are better surfaced as Istio examples and not connected to a particular runtime.` statement as well.

**Comment by gastaldi** [comment]
But I can put it back if necessary

**Comment by Ladicek** [comment]
Well you have a list directly below "The following mission should be removed", and that list only has those 3 Istio examples that are discontinued. My understanding is that the Tracing example should still be maintained and included in the catalog.

**Pull request merged**
