### PR TITLE
DO NOT MERGE: Update Spring Boot to 1.5.15

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
@metacosm Can you take a look please?

**Comment by gastaldi** [comment]
[test]

**Comment by Ladicek** [comment]
@metacosm Not yet, no: https://github.com/fabric8-launcher/launcher-booster-catalog/pull/225

**Comment by geoand** [comment]
Closing in favor of #281 that contains the necessary update to `metadata.yaml`. Sorry for the inconvenience

**Pull request closed without merging**
