### PR TITLE
SB-541: Remove 1.5.8 version of Spring Boot boosters.

### PR DESCRIPTION
**Pull request by metacosm**

### CODE REVIEW

**Comment by quintesse** [comment]
Shall we do this now @metacosm ? Or do we wait a bit more in the hope that the runtime will appear before we do the release?

**Comment by metacosm** [comment]
@quintesse that is the question, isn't it? :)

**Comment by quintesse** [comment]
Sorry @metacosm , we broke your PRs. I'm afraid you'll probably have to redo them because with the new catalog layout they will never apply cleanly. Instead of Missions being the top level folder in the catalog they are now the bottom one, with Runtimes and Versions being the new top level and second level folder respectively.

**Comment by gastaldi** [comment]
@metacosm you need to add the `worksWithLegacyOsio: true` in the 1.5.10 version

**Comment by gastaldi** [comment]
Also make sure to squash your commits into a single one ;)

**Comment by metacosm** [comment]
Well, to be fair, with respect to squashing, there only was one commit but I performed the update here because the change to vert.x (which actually was created later than this PR) was merged before…

**Comment by metacosm** [comment]
@gastaldi why do I need the `worksWithLegacyOsio` bit?

**Comment by gastaldi** [comment]
@metacosm because that's how we do right now to identity the boosters that work in openshift.io

**Comment by metacosm** [comment]
@gastaldi ok, but I have no idea if the boosters work in openshift.io :) I don't have access to it so I don't have tested that scenario.

**Comment by gastaldi** [comment]
@metacosm any changes pushed to the master branch in booster-catalog are consumed also in https://prod-preview.openshift.io. To get an account in OSIO, follow these steps: https://openshift.io/osiogettingstarted.pdf

**Comment by metacosm** [comment]
@gastaldi boosters that were compatible (http and health check) have been marked in #168

**Pull request merged**
