### PR TITLE
supress the community runtime versions in the osio

### PR DESCRIPTION
**Pull request by animuk**
supress the community runtime versions in the osio so that only rhoar version is used

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Any particular reason for this change?

**Comment by animuk** [comment]
As per stefan, We will simplify the application creation process by taking the rhoar version by default and not giving choice to the user to choose the community versions of the booster in osio new experience flow.

**Comment by metacosm** [comment]
Too bad as some boosters might end up being community-only. Plus, I'd expect most of the innovation to happen on the community side first as well.

**Comment by gastaldi** [comment]
@slemeur @qodfathr is that an accurate information? I need your +1 in this PR before accepting it. Not allowing the user to choose between the community or the RHOAR version seems odd to me

**Comment by slemeur** [comment]
@gastaldi : The difference between a RHOAR version and a community version for a booster is unclear to me. My assumption is that a RHOAR version is "productized" and relying only on red hat dependencies. Could you clarify if I'm mistaken?

For the time being, we should be enabling only the RHOAR boosters in OSIO. The packaged boosters need to be validated accross all the different tools provided in OSIO and we need to ensure the completeness of the end-to-end experience. At this moment, we only ensure that for the RHOAR versions - so we don't want to bring versions of the boosters who have not been tested accross all OSIO tools.

You can find a list of the acceptance criteria for a booster in the following issue: https://github.com/openshiftio/openshift.io/issues/2358 

In general, I would think that the ideal situation would be that before a new booster version (community or rhoar) is released we ensure those acceptance criterias are checked and added to automate tests for OSIO. 

Separate issue, but still important: how a user is supposed to make the choice between versions of a booster? How should he know the difference between a RHOAR version and a community version? How should he learn the difference between version 1.10 of a booster and version 2 ? Do we maintain that somewhere? 
In the current UX, as a user, I would have no idea about what is being asked to me with the dropdown we have in place. For a new user, this is adding some complexity that we don't want upfront, as part of the getting started experience.

**Comment by metacosm** [comment]
@slemeur Very good points on the UX regarding community vs. prod.

Regarding the difference between RHOAR and community, at the moment, the only difference is in the dependencies but it isn't correct to say that a RHOAR booster only relies on Red Hat dependencies. A RHOAR booster depends on Red Hat dependencies where **possible**. For Spring Boot and Node, this ends up being not that many dependencies out of all made available.

Also, and perhaps more significantly, I think that the launcher should be open to accept missions outside of Red Hat validated ones, meaning that runtimes should be able to provide boosters for scenarios that they think illustrate interesting points to highlight for applications running on OpenShift. Some of these scenarios might not make sense for all the runtimes. Some of these scenarios might not be that important to highlight to justify the RHOAR stamp of approval but still nice to have. In this case, these missions would only be available as community version. 

I do agree that there isn't much value **at the moment** in having both community and supported version since we don't currently provide non-supported missions via the launcher UI. My hope, however, is that this is a transient situation and we do need to deal with the associated UX sooner than later, both for Launcher and OSIO.

**Comment by rdruss** [comment]
Actually, I believe Fuse have created some mission/booster combinations which are outside of the RHOAR product runtimes.  However, this capability is definitely a goal for the Launch Service team as I understand it - allowing booster contributions outside of RHOAR runtimes.

For community vs. RHOAR versions, I know Vert.x has (and will) have the community versions stay as close to community releases as possible.  So, more than likely, there will be at least this difference, but the plan is to change the community release to reflect any changes upstream where applicable.

**Pull request merged**
