### PR TITLE
Update 1.5.10 boosters to use booster-parent 18.

### PR DESCRIPTION
**Pull request by metacosm**

### CODE REVIEW

**Comment by gastaldi** [comment]
[test]

**Comment by metacosm** [comment]
[test]

**Comment by gastaldi** [comment]
@metacosm you need to be in this list to allow [test] to work: https://github.com/openshiftio/openshiftio-cico-jobs/blob/master/devtools-ci-index.yaml#L12

**Comment by quintesse** [comment]
Sorry @metacosm , we broke your PRs. I'm afraid you'll probably have to redo them because with the new catalog layout they will never apply cleanly. Instead of Missions being the top level folder in the catalog they are now the bottom one, with Runtimes and Versions being the new top level and second level folder respectively.

**Comment by gastaldi** [comment]
[test]

**Comment by quintesse** [comment]
LGTM. The 1.5.10 artifacts when been published then?

**Comment by metacosm** [comment]
@quintesse yes, the artifacts are available.

**Comment by quintesse** [comment]
As @gastaldi mentioned on the other PR, you'll need to add this:

```yaml
metadata:
  worksWithLegacyOsio: true
```

to the health-check and rest-http boosters. Otherwise those will disappear from the current openshift.io application.

**Comment by quintesse** [comment]
Some more explanation about that last remark:

It's because in the old code the boosters that work with the current OSIO application were literally hard-coded. That wasn't much of a problem for runtimes that use "community" and "redhat" as version names because the names nbever change. But you guys use the version as part of the name which means we'd have to publish a new version of the app each time you change versions. So we decided to add this simple attribute that marks which boosters can be used in the current (legacy) OSIO app.

**Comment by metacosm** [comment]
Can one of the admins verify this patch?

**Comment by quintesse** [comment]
@centos-ci [test]

**Comment by metacosm** [comment]
Thanks, @quintesse!

**Pull request merged**
