### PR TITLE
Update Spring Boot to 2.2.6.RELEASE

### PR DESCRIPTION
**Pull request by jacobdotcosta**

### CODE REVIEW

**Comment by quintesse** [comment]
[test]

**Comment by quintesse** [comment]
Btw @jacobdotcosta , you don't need to open a new PR. You can just re-do your changes, do a `git commit --amend` and then force-push. Or just add the changes in new commits and I'll squash them into a single commit, no problem. :-)

**Comment by metacosm** [comment]
@quintesse Is it normal that the tests are failing because they're not resolving prod versions of our artifacts which are not supposed to be on Maven Central?

**Comment by Ladicek** [comment]
It is quite normal. Why would you want the Launcher to serve examples that don't work?

**Comment by metacosm** [comment]
> It is quite normal. Why would you want the Launcher to serve examples that don't work?

@Ladicek Care to elaborate? The bits are available on MRRC, just not on Central.

**Comment by Ladicek** [comment]
Ah, sorry, missed that! In that case, no, that test should pass. Hmm, unless for some reason, you removed the MRRC declarations from those POMs, perhaps?

**Comment by metacosm** [comment]
> Ah, sorry, missed that! In that case, no, that test should pass. Hmm, unless for some reason, you removed the MRRC declarations from those POMs, perhaps?

That's indeed what's going on, unfortunately. I got the same hunch that you did and checked and, indeed, the MRRC definition got removed… 😭

**Comment by Ladicek** [comment]
Aaaand the test proves useful :grin:

**Pull request closed without merging**
