### PR TITLE
[SWARM-1857] Update Swarm Community Booster versions

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Comment by gastaldi** [comment]
[test]

**Comment by gastaldi** [comment]
@kenfinnigan @Ladicek is it OK to merge this PR? Can I get a +1 from any of you guys?

**Comment by kenfinnigan** [comment]
+10

Does that count?

**Comment by gastaldi** [comment]
@kenfinnigan thanks

**Comment by Ladicek** [comment]
Sorry for not getting to it sooner, I'd give a -1 because we also need to update the version number in `metadata.yaml` in the root directory of this repo :-)

**Comment by gastaldi** [comment]
@Ladicek can you or someone from your team provide another PR with the version number in `metadata.yaml` updated?

**Comment by Ladicek** [comment]
@gastaldi Can do, but we'll be updating the WildFly Swarm `-redhat` boosters soon, so I guess we can update the metadata at that time.

**Pull request merged**
