### PR TITLE
Revert "Update Spring Boot to 2.1.12"

### PR DESCRIPTION
**Pull request by metacosm**
Reverts fabric8-launcher/launcher-booster-catalog#319
This PR shouldn't have been merged. It's wrong.

### CODE REVIEW

**Comment by metacosm** [comment]
@gastaldi please merge this ASAP as the previous PR shouldn't have been merged.

**Comment by metacosm** [comment]
@gastaldi please merge this ASAP as the previous PR shouldn't have been merged.

**Comment by metacosm** [comment]
@gastaldi thanks!

**Comment by gastaldi** [comment]
@metacosm I'd suggest adding a WIP to the title next time :wink:

**Pull request merged**
