### PR TITLE
update http booster version

### PR DESCRIPTION
**Pull request by cescoffier**
This version should fix the pipeline issue, the broken yaml and so on.... hopefully.

### CODE REVIEW

**Comment by gastaldi** [comment]
[test]

**Comment by quintesse** [comment]
Thanks @cescoffier ! I will wait a little while to merge this so I can test the improved catalog validator, ok? Or do you need this changes applied right away?

**Comment by cescoffier** [comment]
@gastaldi all vert.x boosters have the issue. This one is faster to check. If it works I will update all of them.

**Comment by quintesse** [comment]
@centos-ci [test]

**Comment by quintesse** [comment]
(pity, you can't retest merged PRs hehe)

**Comment by cescoffier** [comment]
@quintesse don't worry, you will get soon a larger PR to test.

**Pull request merged**
