### PR TITLE
Update Spring Boot to 2.1.3

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
@gastaldi I have never seen anybody change an issue title so quick :P :P

**Comment by geoand** [comment]
@metacosm should we now remove `WIP`?

**Comment by metacosm** [comment]
@geoand let me doublecheck first

**Comment by metacosm** [comment]
@geoand nope, it's not available yet.

**Comment by geoand** [comment]
Thanks for checking @metacosm !

**Comment by metacosm** [comment]
@gastaldi once checks are OK, this is OK to be merged.

**Comment by gastaldi** [comment]
[test]

**Pull request merged**
