### PR TITLE
Thorntail 2.7.2

### PR DESCRIPTION
**Pull request by Ladicek**

### CODE REVIEW

**Comment by quintesse** [comment]
[test]

**Review by quintesse — APPROVED** [review]
LGTM

**Comment by penehyba** [comment]
[test]

**Comment by Ladicek** [comment]
Can we retest? The failure is caused by `Failed to collect dependencies at io.thorntail:keycloak:jar:2.7.0.Final: Failed to read artifact descriptor for io.thorntail:keycloak:jar:2.7.0.Final: Could not transfer artifact io.thorntail:keycloak:pom:2.7.0.Final from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.248.215] failed: Connection timed out`.

**Comment by quintesse** [comment]
[test]

**Comment by Ladicek** [comment]
Hi @quintesse, could you please merge? I can push the button, but I don't think I can do a release, so I'd have to ask you anyway :-) Thanks!

**Comment by quintesse** [comment]
Done and released!

**Comment by Ladicek** [comment]
Thanks again!

**Pull request merged**
