### PR TITLE
Thorntail 2.7

### PR DESCRIPTION
**Pull request by Ladicek**

### CODE REVIEW

**Comment by quintesse** [comment]
[test]

**Comment by Ladicek** [comment]
Can we get this merged, pretty please? :-) Thanks!

**Comment by Ladicek** [comment]
Thank you!

**Comment by Ladicek** [comment]
Hi @quintesse, this was tagged (in https://github.com/fabric8-launcher/launcher-booster-catalog/releases/tag/v132), but the Launcher still shows Thorntail 2.5. Did anything change? Thanks!

**Comment by quintesse** [comment]
The server was still caching things, should be okay now.

**Comment by Ladicek** [comment]
Perfect, thanks!

**Pull request merged**
