### PR TITLE
Icons

### PR DESCRIPTION
**Pull request by edewit**
added icon to runtime, to decouple front-end from booster-catalog see issue https://github.com/fabric8-launcher/launcher-planning/issues/73

### CODE REVIEW

**Comment by gastaldi** [comment]
Why the SVG files if the data is entirely in the metadata.json?

**Comment by edewit** [comment]
@gastaldi just wanted to add them to know where the data is coming from

**Comment by gastaldi** [comment]
But do you think it makes sense to have them in the repository even if we are not using them?

**Comment by edewit** [comment]
okay lets remove them

**Comment by quintesse** [comment]
@gastaldi I would actually say it *does* make sense. What if you want to edit the SVG and then re-apply it to the .json file? Wouldn't it be better to have the originals available?

**Comment by gastaldi** [comment]
Then I think we should have a path instead and transform it into base64 during the indexing process

**Pull request merged**
