### PR TITLE
chore: update node.js istio circuit breaker booster to Istio 1.0.0 ve…

### PR DESCRIPTION
**Pull request by lholmquist**
…rsion

just test with the latest istiooc launcher(https://github.com/openshift-istio/origin/releases), and it looks like only one booster needed an update.

### CODE REVIEW

**Comment by lholmquist** [comment]
adding a WIP to the title since there is a new istiooc command release i want to try out

**Comment by gastaldi** [comment]
[test]

**Comment by lholmquist** [comment]
going to put this back to WIP.  i forgot to add the "-redhat" versions of the boosters

**Comment by gastaldi** [comment]
[test]

**Pull request merged**
