### PR TITLE
Update catalog for 3.6.3 Vert.x product release

### PR DESCRIPTION
**Pull request by rdruss**

### CODE REVIEW

**Comment by gastaldi** [comment]
[test]

**Comment by gastaldi** [comment]
[test]

**Comment by gastaldi** [comment]
[test]

**Comment by gastaldi** [comment]
@Ladislav it looks like the booster-catalog-verifier is locked up while testing a Thorntail test, can you check?

**Comment by Ladicek** [comment]
Will check.

**Pull request merged**
