### PR TITLE
WIP: Updated Vert.x version to 3.9.5 and 4.0.0

### PR DESCRIPTION
**Pull request by akoniar**

### CODE REVIEW

**Comment by quintesse** [comment]
[test]

**Comment by quintesse** [comment]
Saw this PR was still unmerged, sorry about that. Is it still up-to-date and mergeable?

**Comment by akoniar** [comment]
@quintesse Now it's up to date. But I haven't test the examples (boosters) on this versions. I'll test the examples and after that you can merge it

**Comment by quintesse** [comment]
[test]

**Comment by quintesse** [comment]
I'll wait for your okay then 👍

**Comment by quintesse** [comment]
Stale PR. Closing.

**Pull request closed without merging**
