### PR TITLE
Thorntail 2.7.3, part 2

### PR DESCRIPTION
**Pull request by Ladicek**
I had to release Thorntail 2.7.3 examples again to fix a bug
in S2I flow testing.

### CODE REVIEW

**Comment by quintesse** [comment]
[test]

**Comment by quintesse** [comment]
Seems you forgot to update the metadata, right?

**Comment by Ladicek** [comment]
Not really, that was updated in #412. I added one YAML to `.openshiftio` in the Istio example, and the validator doesn't like that it's a multidocument YAML. Hmm...

**Comment by Ladicek** [comment]
I think I can just change that YAML file to use `kind: List` and be done with it... hopefully :-) I'll try that.

**Comment by Ladicek** [comment]
Done that, could you please trigger retest? Thanks!

**Comment by quintesse** [comment]
[test]

**Comment by Ladicek** [comment]
Passed, yay :-)

**Pull request merged**
