### PR TITLE
Update Spring Boot to 1.5.19

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
[test]

**Comment by gytis** [comment]
LGTM

**Comment by geoand** [comment]
@gytis can you please approve so the PR will be unblocked? Thanks

**Comment by gastaldi** [comment]
[test]

**Comment by geoand** [comment]
Thanks @gastaldi !

**Comment by geoand** [comment]
@gastaldi have the changes been reflected in production?

Thanks!

cc @liborfuka

**Comment by gastaldi** [comment]
@geoand sorry, I forgot to create a release. It is now, thanks for catching this :)

**Comment by geoand** [comment]
No problem at all, thanks for your help @gastaldi

**Comment by liborfuka** [comment]
@gastaldi Is there any time delay between release and time when i can see 1.5.19 on drop down list on https://developers.redhat.com/launch/flow/deploy-example-app?

**Pull request merged**
