### PR TITLE
Update Spring Boot to 1.5.19

### PR DESCRIPTION
**Pull request by metacosm**

### CODE REVIEW

**Comment by gytis** [comment]
LGTM

**Comment by liborfuka** [comment]
These versions were not tested by QE.
1.5.19-3-redhat tag was tested.

**Comment by gastaldi** [comment]
[test]

**Comment by geoand** [comment]
@lfuka could you test the latest releases of the boosters please?

**Comment by liborfuka** [comment]
Sure, please wait with merging to finishing the tests.

**Comment by geoand** [comment]
Sure thing

**Comment by liborfuka** [comment]
Booster tests passed for 1.5.19-4-redhat and http-rest 1.5.19-6-redhat

**Comment by geoand** [comment]
Thanks @liborfuka !

**Pull request merged**
