### PR TITLE
Update Spring Boot to 2.4.9

### PR DESCRIPTION
**Pull request by jacobdotcosta**

### CODE REVIEW

**Comment by quintesse** [comment]
[test]

**Comment by quintesse** [comment]
Still getting errors it seems...

**Comment by jacobdotcosta** [comment]
The problem seems to be the junit version.

```
[INFO] Compiling 1 source file to /tmp/junit8379195045101937131/spring-boot/booster4266474215477127666/name-service/target/test-classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /tmp/junit8379195045101937131/spring-boot/booster4266474215477127666/name-service/src/test/java/dev/snowdrop/example/NameEndpointTest.java:[21,17] package org.junit does not exist
[ERROR] /tmp/junit8379195045101937131/spring-boot/booster4266474215477127666/name-service/src/test/java/dev/snowdrop/example/NameEndpointTest.java:[22,17] package org.junit does not exist
[ERROR] /tmp/junit8379195045101937131/spring-boot/booster4266474215477127666/name-service/src/test/java/dev/snowdrop/example/NameEndpointTest.java:[23,24] package org.junit.runner does not exist
[ERROR] /tmp/junit8379195045101937131/spring-boot/booster4266474215477127666/name-service/src/test/java/dev/snowdrop/example/NameEndpointTest.java:[30,2] cannot find symbol
  symbol: class RunWith
[ERROR] /tmp/junit8379195045101937131/spring-boot/booster4266474215477127666/name-service/src/test/java/dev/snowdrop/example/NameEndpointTest.java:[42,6] cannot find symbol
  symbol:   class Before
  location: class dev.snowdrop.example.NameEndpointTest
[ERROR] /tmp/junit8379195045101937131/spring-boot/booster4266474215477127666/name-service/src/test/java/dev/snowdrop/example/NameEndpointTest.java:[47,6] cannot find symbol
  symbol:   class Test
  location: class dev.snowdrop.example.NameEndpointTest
[ERROR] /tmp/junit8379195045101937131/spring-boot/booster4266474215477127666/name-service/src/test/java/dev/snowdrop/example/NameEndpointTest.java:[52,6] cannot find symbol
  symbol:   class Test
  location: class dev.snowdrop.example.NameEndpointTest
[ERROR] /tmp/junit8379195045101937131/spring-boot/booster4266474215477127666/name-service/src/test/java/dev/snowdrop/example/NameEndpointTest.java:[57,6] cannot find symbol
  symbol:   class Test
  location: class dev.snowdrop.example.NameEndpointTest
[INFO] 8 errors 
```

@quintesse is there the possibility of using a junit 5 capable system for this example?

**Comment by quintesse** [comment]
@jacobdotcosta it's your code so you people can do with it what you want :-)
Just make sure it compiles before you create the PR because the problem is simply that it doesn't compile, not even when I clone it locally and simply run `./mvn package`.

**Comment by jacobdotcosta** [comment]
I see the problem. It should be using example version `2.4.9-9` instead of `2.4.9-8`. I apologize for this.

**Pull request closed without merging**
