### PR TITLE
Change node examples from Node.js 12.x to 14.x

### PR DESCRIPTION
**Pull request by alexalikiotis**

### CODE REVIEW

**Review by lholmquist — APPROVED** [review]

**Comment by lholmquist** [comment]
[test]

**Comment by quintesse** [comment]
[test]

**Comment by lholmquist** [comment]
[test]

**Review by lholmquist — APPROVED** [review]

**Comment by lholmquist** [comment]
@quintesse do you need to write [test],  not sure if my [test] kicks anything off

**Comment by quintesse** [comment]
[test]

**Comment by quintesse** [comment]
Sorry @lholmquist , it only seems to work when I do it

**Pull request merged**
