### PR TITLE
Update Spring Boot to 2.1.6

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
[test]

**Comment by gastaldi** [comment]
[test]

**Comment by geoand** [comment]
@gastaldi any idea why CI is failing? @liborfuka tested the boosters and verified they work

**Comment by gastaldi** [comment]
Hum, I tried locally and I see the same error when `mvn clean package`ing with the `2.1.6-5-redhat` tag. Where is the MRRC repository declared? In https://github.com/snowdrop/health-check-example/blob/2.1.3-2-redhat/pom.xml#L19-L23 the pom.xml uses the booster-parent as the parent pom. 

I still think something like this is missing: https://github.com/openshift-vertx-examples/vertx-health-checks-example-redhat/blob/v22/pom.xml#L168-L192

@liborfuka can you test by removing the productized versions from your local repository and disabling any reference to the MRRC in your settings.xml?

**Comment by geoand** [comment]
Closing since a new version is incoming

**Pull request closed without merging**
