### PR TITLE
Add Thorntail project metadata and move Istio Boosters under Thorntail

### PR DESCRIPTION
**Pull request by kenfinnigan**
Also update Istio Boosters to latest tag

### CODE REVIEW

**Comment by gastaldi** [comment]
[test]

**Comment by gastaldi** [comment]
Will the WildFly Swarm runtime still exist in the catalog or will that be moved to Thorntail in a later step ?

**Comment by kenfinnigan** [comment]
There will be a PR soon to move the remainder of the community ones to thorntail. But WildFly Swarm will still be there for product until a release later this year

**Comment by gastaldi** [comment]
Don't forget to change the https://github.com/fabric8-launcher/launcher-booster-catalog/blob/master/.github/CODEOWNERS file too, since this is a new directory

**Comment by kenfinnigan** [comment]
Do you want the codeowners change in this PR?

**Comment by gastaldi** [comment]
[test]

**Pull request merged**
