### PR TITLE
Add SB ConfigMap booster adapted for OSIO

### PR DESCRIPTION
**Pull request by gytis**
@gastaldi @quintesse I've created an `osio` branch in a Spring Boot ConfigMap booster repo to adapt it for OSIO. Could you verify this via Launcher?

### CODE REVIEW

**Comment by gytis** [comment]
For now we just need to verify this works. We still need to confirm if this needs to be community, prod or both.

**Comment by metacosm** [comment]
@gytis it will probably use the prod artifacts… :(

**Comment by gytis** [comment]
OK I'm going to rework it to use productised dependencies.

**Comment by quintesse** [comment]
@gytis I think we need a `runsOn: '!osio'` in `current-redhat` too

**Comment by gytis** [comment]
Raised a separate PR https://github.com/fabric8-launcher/launcher-booster-catalog/pull/205

**Comment by metacosm** [comment]
No, I don’t have any visibility on the sync process…

**Pull request merged**
