### PR TITLE
ENTSWM-250: Release new prod boosters (free branch)

### PR DESCRIPTION
**Pull request by heiko-braun**

### CODE REVIEW

**Comment by heiko-braun** [comment]
@Ladicek Mind a review or quick test?

**Comment by heiko-braun** [comment]
@gastaldi Can you take these changes online?

**Comment by gastaldi** [comment]
Sure, I'll tag the repository and update prod. Thanks!

**Comment by heiko-braun** [comment]
@gastaldi Can you drop me a note when things should appear online?

**Comment by gastaldi** [comment]
@heiko-braun I have created https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/1015, it's up to the Service Delivery team now to perform the change. You can subscribe to the issue to be notified when that happens in case I forget to notify you.

**Pull request merged**
