### PR TITLE
Update Spring Boot to 2.1.6

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by gastaldi** [comment]
[test]

**Comment by geoand** [comment]
CI is failing with the same error we were seeing in the other 2.1.6 PR attempts. 

I don't understand why this happens since the PRs is essentially the same as the older version (2.1.3 for example).
Plus the changes have been verified by QE (@liborfuka )

**Comment by geoand** [comment]
We might have figured this out

**Comment by geoand** [comment]
Closing, will follow up with a new one soon

**Pull request closed without merging**
