### PR TITLE
Udated to Fuse 7.6 release.

### PR DESCRIPTION
**Pull request by valdar**

### CODE REVIEW

**Comment by quintesse** [comment]
[test]

**Comment by quintesse** [comment]
Btw, I see that you guys are keeping all the old Fuse versions . Is that something you are doing on purpose? Other runtimes only keep the latest stable release or perhaps a stable release and a new release still being worked on. (Not saying you can't do it this way, just wondering if you had a particular reason)

**Comment by valdar** [comment]
@quintesse yep, we do it on purpose since that is linked to the documentation for the given version, sort of official way to distribute those examples that need to remain there.

**Comment by quintesse** [comment]
Ok, perfect, good to know! 👍

**Pull request merged**
