### PR TITLE
Update Spring Boot to 2.1.6

### PR DESCRIPTION
**Pull request by aureamunoz**

### CODE REVIEW

**Comment by gastaldi** [comment]
[test]

**Comment by geoand** [comment]
[test]

**Comment by geoand** [comment]
[retest this please]

**Comment by gastaldi** [comment]
[ok to test]

**Comment by gastaldi** [comment]
[test]

**Comment by gastaldi** [comment]
@aureamunoz @geoand it looks like there is something wrong with the SB RedHat examples, can you check why the build fails?

**Comment by aureamunoz** [comment]
Hello! I'll take a look

**Comment by geoand** [comment]
@gastaldi hey

**Comment by gastaldi** [comment]
@geoand how is the MRRC repository enabled in the example? Not sure why it tries to use the Central repo to resolve productized dependencies

**Comment by geoand** [comment]
@gastaldi there is nothing special being done to enable it.

The weird thing is that nothing in that sense has changed between this PR and the previous PR.

**Comment by gastaldi** [comment]
[test]

**Comment by gastaldi** [comment]
@geoand it seems that the productized example does not inherit from `io.openshift:booster-parent:23` (which declares the MRRC: https://github.com/openshiftio/booster-parent/blob/master/pom.xml#L279-L303)

Other runtimes (like the Thorntail ones) declare the repository in the pom, like in https://github.com/thorntail-examples/configmap-redhat/blob/master/pom.xml#L140-L164 maybe that's what's missing?

**Comment by geoand** [comment]
Perhaps, we'll have to look into this. Thanks

**Comment by geoand** [comment]
Closing, will open a follow up

**Pull request closed without merging**
