### PR TITLE
Disable springboot-configmap, wildfly-swarm-configmap and wildfly-swarm-health-check booster

### PR DESCRIPTION
**Pull request by ravsa**
Build for springboot-configmap, wildfly-swarm-configmap and wildfly-swarm-health-check boosters are failing so disabling that.

Logs:
Springboot-configmap: https://github.com/openshiftio/openshift.io/issues//3131
Wildfly-Swarm-configmap: https://github.com/openshiftio/openshift.io/issues//3134
Wildfly-Swarm-health-check: https://github.com/openshiftio/openshift.io/issues//3124

### CODE REVIEW

**Comment by gastaldi** [comment]
@ravsa the SB configmap booster was just updated l. Can you verify if it works correctly in prod-preview and update this PR?

**Comment by gastaldi** [comment]
[test]

**Comment by gastaldi** [comment]
@animuk have you seen my comment in https://github.com/fabric8-launcher/launcher-booster-catalog/pull/209#issuecomment-386242504? I was waiting for a reply from @ravsa before this PR is merged

**Comment by metacosm** [comment]
Actually, the `current-osio` version of the SB configmap was specifically created to work with OSIO…

**Pull request merged**
