### PR TITLE
Updated runtime descriptions. Fixes fabric8-launcher/launcher-planning#147

### PR DESCRIPTION
**Pull request by rhoads-zach**

### CODE REVIEW

**Comment by rhoads-zach** [comment]
fixes https://github.com/fabric8-launcher/launcher-planning/issues/147

**Comment by gastaldi** [comment]
@jyasveer can you confirm if the descriptions provided here are sufficient to resolve your https://github.com/fabric8-launcher/launcher-planning/issues/147 issue?

**Comment by gastaldi** [comment]
I'll merge this and we can reopen the issue if it needs any further adjustment

**Comment by gastaldi** [comment]
Thanks @rhoads-zach !

**Comment by rhoads-zach** [comment]
np, thank you @gastaldi

**Pull request merged**
