### PR TITLE
Update Spring Boot to 2.4.9

### PR DESCRIPTION
**Pull request by jacobdotcosta**

### CODE REVIEW

**Comment by jacobdotcosta** [comment]
[test]

**Comment by quintesse** [comment]
[test]

**Comment by quintesse** [comment]
@jacobdotcosta I would love to be able to give you rights to start the tests yourself, but I haven't set this stuff up and I don't really know how it works :sweat_smile:

**Comment by jacobdotcosta** [comment]
It was worth to try!

**Pull request merged**
