### PR TITLE
Update Spring Boot boosters

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
This change is needed because of an issue with the previous boosters release that was not caught in time (we have taken steps to ensure that it won't happen again).

Internal tests are running on the new releases as we speak. When they pass, I will update the title of the PR

**Comment by geoand** [comment]
[test]

**Comment by geoand** [comment]
Internal tests have passed

**Comment by gastaldi** [comment]
[test]

**Comment by geoand** [comment]
Thanks @gastaldi

**Pull request merged**
