### PR TITLE
Remove Istio Distributed Tracing examples for Spring Boot

### PR DESCRIPTION
**Pull request by geoand**
According to @liborfuka this should be removed

### CODE REVIEW

**Comment by Ladicek** [comment]
That doesn't sound right. @liborfuka can you comment why distributed tracing is to be removed?

**Comment by liborfuka** [comment]
because it has bugs, its not tested even supported.

**Comment by liborfuka** [comment]
@mocenas

**Comment by Ladicek** [comment]
Testing should be performed and bugs should be fixed :-) My understanding is that we intentionally removed _almost_ all the Istio boosters, _except_ Distributed Tracing. If you've reached an agreement with PM to remove this one, then by all means go ahead :-)

**Comment by mocenas** [comment]
@Ladicek You are right. But as @liborfuka mentioned the istio boosters are buggy. I'm not sure if there is any blocker for DT right now. Some other istio booster definitely have serious issues which are not fixed for quite a time.
Also non of the istio boosters were tested for 2.1.6. Also they doesn't seems to be maintained.
I'm not sure what did PM said about this, but in reality the istio boosters are now a shame for us. So I think we should not present them publicly.

**Comment by gastaldi** [comment]
Can this be merged now?

**Comment by liborfuka** [comment]
wait for our PM Naina please.

**Comment by gastaldi** [comment]
What's the outcome of this PR?

**Comment by geoand** [comment]
@liborfuka ^

**Comment by gastaldi** [comment]
Closing as this PR needs to be rebased. Please rebase and reopen if necessary

**Pull request closed without merging**
