### PR TITLE
Update booster catalog with Thorntail 2.3.0 aligned boosters

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Comment by gastaldi** [comment]
[test]

**Comment by sberyozkin** [comment]
@gastaldi, thanks, gedit crashes when I try to open metadata.yaml, LibreWriter messes up the formatting when saving in the text mode. How to edit it :-) ?

**Comment by gastaldi** [comment]
There is a nice editor called `vi` :smile:.

**Comment by sberyozkin** [comment]
You are right :-). I need to get back to it from gedit. Thought it added the extra new line at the end of the file which is prob OK

**Comment by gastaldi** [comment]
[test]

**Comment by gastaldi** [comment]
Thank you!

**Comment by sberyozkin** [comment]
Thanks

**Pull request merged**
