### PR TITLE
Updated to release 1.1

### PR DESCRIPTION
**Pull request by valdar**

### CODE REVIEW

**Comment by aileenc** [comment]
PR has been merged but I don't see Fuse listed yet on https://launch.openshift.io

What else needs to happen for us to show up there?

**Comment by gastaldi** [comment]
We haven't promoted to production yet. It is in the staging environment only at the moment: https://launch.prod-preview.openshift.io/launch/

And the production URL is https://developers.redhat.com/launch/ :)

**Comment by gastaldi** [comment]
We can do that today, if we get a +1 from your QA team that this booster works in the staging environment

**Comment by valdar** [comment]
Shouldn't be added as "Supported Runtimes" in beta in the homepage as well i.e. hitting https://launch.prod-preview.openshift.io/launch/ ?

**Comment by gastaldi** [comment]
That would require changes in the launcher-frontend.

**Comment by valdar** [comment]
@gastaldi PR created for the frontend https://github.com/fabric8-launcher/launcher-frontend/pull/232

**Pull request merged**
