### PR TITLE
Update Spring Boot to 2.1.6

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
Don't merge please until @liborfuka has tested the new version of the boosters

**Comment by gastaldi** [comment]
[test]

**Comment by geoand** [comment]
[retest this please]

**Comment by gastaldi** [comment]
[test]

**Comment by gastaldi** [comment]
@geoand looks like it works now! :fireworks:

**Comment by geoand** [comment]
At long last 🙃

**Comment by liborfuka** [comment]
Booster tests passed. You can merge PR.

**Comment by geoand** [comment]
@gastaldi do you want to do a release or should I?

**Comment by gastaldi** [comment]
@geoand by all means ;)

**Comment by geoand** [comment]
Done, thanks :)

**Pull request merged**
